name: Build and run functional tests using ragger through reusable workflow

# This workflow will build the app and then run functional tests using the Ragger framework upon Speculos emulation.
# It calls a reusable workflow developed by Ledger's internal developer team to build the application and upload the
# resulting binaries.
# It then calls another reusable workflow to run the Ragger tests on the compiled application binary.
#
# While this workflow is optional, having functional testing on your application is mandatory and this workflow and
# tooling environment is meant to be easy to use and adapt after forking your application

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
      - liquid_develop
  pull_request:

jobs:
  build_application:
    name: Build regtest application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: "compiled_app_binaries_regtest"
      flags: "DEBUG=0 COIN=liquid_regtest"

  ragger_tests:
    name: Run ragger tests for regtest application using the reusable workflow
    needs: build_application
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@v1
    with:
      download_app_binaries_artifact: "compiled_app_binaries_regtest"
      test_dir: "tests_liquid"

  build_application_testnet:
    name: Build testnet application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: "compiled_app_binaries_testnet"
      flags: "DEBUG=0 COIN=liquid_testnet"

  ragger_tests_testnet:
    name: Run ragger tests for testnet application using the reusable workflow
    needs: build_application_testnet
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@v1
    with:
      download_app_binaries_artifact: "compiled_app_binaries_testnet"
      test_dir: "tests_liquid_testnet"

